name: asset_manager
description: "A new Flutter project."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'


dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.6
  flutter_localization: ^0.2.0
  uuid: ^4.4.2
  flutter_riverpod: ^2.5.1
  image_picker: ^1.1.2
  location: ^6.0.2
  http: ^1.2.2
  google_maps_flutter: ^2.9.0
  path_provider: ^2.1.4
  path: ^1.9.0
  sqflite: ^2.3.3+1
  intl: ^0.19.0
  google_fonts: ^6.2.1


dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^3.0.0


flutter:


  uses-material-design: true


