name: asset_manager
description: "A new Flutter project."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'


dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.6
  flutter_localization: ^0.2.2
  uuid: ^4.4.2
  flutter_riverpod: ^2.5.1
  image_picker: ^1.1.2
  location: ^6.0.2
  http: ^1.2.2
  google_maps_flutter: ^2.9.0
  path_provider: ^2.1.4
  path: ^1.9.0
  sqflite: ^2.3.3+1
  google_fonts: ^6.2.1
  barcode_widget: ^2.0.4
  flutter_barcode_scanner: ^2.0.0
  shared_preferences: ^2.3.2
  flutter_localizations:
    sdk: flutter
  intl: any
  animated_splash_screen: ^1.3.0
  lottie: ^3.1.2
  flutter_native_splash: ^2.4.1
  stylish_bottom_bar: ^1.1.0


dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^3.0.0


flutter:
  generate: true


  uses-material-design: true
  assets:
    - assets/animation/
    - assets/images/
flutter_intl:
  enabled: true

